name: Tests
on:
  push:
    branches:
      - main
      - dev
      - master

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    steps:
      - name: Say Hello World
        shell: bash
        run: echo Welcome to the Github Actions workshop !