name: Tests
on:
  pull_request:
    branches:
      - main
      - dev
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run Tests
        shell: bash
        run: make tests_run
      
      - name: Get Coverage
        if: ${{ always() }}
        shell: bash
        run: make coverage > coverage_output
        
      - name: Upload Coverage Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage_output
          path: ./coverage_output